# User Settings | Edit these according to your site

title: Projet - La Paie en Java
email: italikdesignbordeaux@gmail.com
author: marlenech

description: > # this means to ignore newlines until "baseurl:"
  Chaplin is a minimalistic, mobile friendly theme for Jekyll.
  The Documentation for it is available on this website itself. 
  You can check out the source on <a href="http://github.com/bk2dcradle/Chaplin" class="deactivate-link"><span> GitHub </span></a>

url: "http://marlenech.gitub.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: ItalikDesign
github_username:  marlenech

permalink:          /:year/:title.html

paginate: 4
paginate_path: "/page/:num"
comments: true

heading_font: Lobster 
about_footer: true
short_bio: >
    La nuit je code... et le jour, je suis gestionnaire de paie.
profile_picture: https://avatars3.githubusercontent.com/u/14965403?v=3&s=466

google_analytics: true
tracking_id: 

# Build settings | Do not edit anything below this
markdown: kramdown

gems:
  - jekyll-paginate

sass:
  style:            compressed
  sass_dir:         _sass

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
